// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // `.expo/types` is generated by expo-router's typegen, not authored here.
    ignores: ["dist/*", ".expo/*"],
  }
]);
